### PR TITLE
Files for French Translation

### PR DESCRIPTION
**Pull request by Christophe85**
Hello,

As planned I translated you the 2 files. Let me know if it is ok for you. It's the first time that I do this.

Thanks.

### CODE REVIEW

**Comment by paulgessinger** [comment]
Hey @Christophe85! I merged this now.

However, I noticed that I based the french strings file on the english one, which relies a lot on defaults and is not complete. I updated the french strings file now with the missing strings based on the german strings file, so that it should hopefully now contain all required strings (🤞).

If you have another minute, maybe you can have another go at the new strings?

**Comment by paulgessinger** [comment]
I also pushed build 24 to TestFlight which includes the translations you added so far.

**Comment by Christophe85** [comment]
Hello Paul,

I have translated the file. I am not expert with github but I have deleted my old Fork as you asked for and I created a new one with the file translated.

tell me if it is ok... 

I can't wait for the new version on testflight that includes this file.

Have a nice day.

**Comment by paulgessinger** [comment]
I think you'd have to open a new PR using your `main` branch. Could you try that?

**Pull request merged**
