### PR TITLE
feat: Add ability to login using an access token

### PR DESCRIPTION
**Pull request by RedcedarGeoff**
Allow a user to login with an access token by leaving the username field blank and placing the access token in the password field.

The user interaction/flow/UI for this as it is implemented now is far from ideal. If I could get some direction on how this interaction should/could be, I will make the changes.

### CODE REVIEW

**Comment by paulgessinger** [comment]
Hey @RedcedarGeoff! Thanks for this PR! I'll give this a try on the weekend and then get back to you!

**Comment by paulgessinger** [comment]
Hey @RedcedarGeoff I finally got a chance to check it out and test it on my end! Looks good to me and it's working.

I'm ok to merge this as is and follow this up with some UI, or you can change the PR to include UI for it if you want.

I guess in terms of UI I have two ideas:

1. Keep the basics of the UI as is, change "Password" to "Password / Token", and then put a `?` SF Symbol to the right. Tapping on that symbol opens a basic dialog explaining to leave the username empty for token login.
2. Use a switch or a picker to choose between password and token login, and then effectively just hide the username field and change the password placeholder text to "Token"

Let me know what you think!

**Comment by RedcedarGeoff** [comment]
@paulgessinger I'm happy to make those UI changes. I'll try both suggestions and see what looks/feels right.

Based on issue #21, adding the `Authorization` manually could also work, but that the management of the `Authorization` header seems fairly deeply embedded in the logic, and would require some major refactoring in order to go that route?

**Comment by paulgessinger** [comment]
You're right that explicitly setting the Authorization header would be relatively involved, I think.
To me handling this on the login screen seems like the better approach at this time.

**Comment by paulgessinger** [comment]
@JamesRy96 I have an alternative implementation that's at the top of my list as soon as the iOS 18 update is ready.

**Comment by paulgessinger** [comment]
An alternative to this is now available for testing in build 106 on TestFlight. I'm closing this PR.

@JamesRy96

**Pull request closed without merging**
